name: Continous Deployment

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      tag: ${{ steps.release.outputs.tag_name }}
      released: ${{ steps.release.outputs.releases_created}}
    steps:
      - name: Create release
        id: release
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          release-type: simple
