name: Continous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  schedule:
    - cron: "0 0 1 * *"

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Check dependencies, misconfigurations, and secrets
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          scan-type: fs
          scan-ref: .
          ignore-unfixed: true
          scanners: "vuln,secret,misconfig"
          severity: "HIGH,CRITICAL"
          exit-code: 1
